#主配置文件

spring:
  # 激活环境配置
  profiles:
    active: dev
  # 文件编码 UTF8
  mandatory-file-encoding: UTF-8
  mvc:
    # 404 交给异常处理器处理
    throw-exception-if-no-handler-found: true
  resources:
    # 关闭静态资源的映射
    add-mappings: true


mybatis-plus:
  configuration:
    # 开启下划线转驼峰
    map-underscore-to-camel-case: true
  global-config:
    # 开启/关闭 banner 打印
    banner: false
    db-config:
      # 逻辑删除（软删除）
      logic-delete-value: NOW()
      logic-not-delete-value: 'NULL'
  # mapper路径位置
  mapper-locations: classpath:mapper/*.xml


logging:
  # 日志配置文件（logback配置文件）
  config: classpath:logback-spring.xml


lin:
  cms:
    # 开启行为日志记录（logger）
    logger-enabled: true
    # access token 过期时间，3600s 一个小时
    token-access-expire: 3600
    # refresh token 过期时间，2592000s 一个月
    token-refresh-expire: 2592000
    # 令牌 secret
    token-secret: x88Wf0991079889x8796a0Ac68f9ecJJU17c5Vbe8beod7d8d3e695*4
    websocket:
      enable: true

wx:
  code2session: https://api.weixin.qq.com/sns/jscode2session?appid={0}&secret={1}&js_code={2}&grant_type=authorization_code
  appid: wx24ba6cff6d3637c0
  appsecret: c931cc50a052483556f99d3ccb324145

missyou:
  security:
    jwt-key: 7777777yue
    token-expired-in: 86400000
  order:
    year-code: A,B,C,D,E,F,G,H,I,J,K,L,M
    max-sku-limit: 777
    pay-time-limit: 3600
    pay-callback-host: http://talelin.com
    pay-callback-path: /v1/payment/wx/notify

rocketmq:
  consumer:
    consumer-group: DessertHouseConsumerGroup
  producer:
    producer-group: DessertHouseProducerGroup
  namesrv-addr: 101.33.125.160:9876